all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: "ubuntu"
          #ansible_password: "{{ ansible_vault_password }}"
          hostname: AnsibleMaster
    prod:
      hosts:
        worker01: 
          ansible_host: 172.31.89.176
          hostname: AnsibleWorker01
          ansible_user: "ubuntu"
        worker02: 
          ansible_host: 172.31.93.204
          hostname: AnsibleWorker02
          ansible_user: "centos"
      vars:
        env: "production"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        #ansible_password: "{{ ansible_vault_password }}"
