---
- name: "Script Web Deployment"
  become: yes
  hosts: worker02
  vars:
    web_package: nginx

  tasks:
    - name: "Copy Script "
      template:
        src: "desinstall_nginx.sh.j2"
        dest: "/home/{{ ansible_user }}/desinstall_nginx.sh"

    - name: "Execute Script"
      command: "sh /home/{{ ansible_user }}/desinstall_nginx.sh"