---
- name: "Script Web Deployment"
  become: yes
  hosts: prod
  vars:
    web_package: nginx

  tasks:
    - name: "Copy Script "
      template:
        src: "install_nginx.sh.j2"
        dest: "/home/{{ ansible_user }}/install_nginx.sh"
 
    - name: "Execute Script"
      command: "sh /home/{{ ansible_user }}/install_nginx.sh"