all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
    prod:
      hosts:
        worker01:
          ansible_host: 172.31.93.31
        worker02:
          ansible_host: 172.31.91.167
      vars:
        env: production    

    
