all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: ubuntu
          hostname: AnsibleMaster
    prod:
      hosts:
        worker01: 
          ansible_host: 172.31.93.31
          hostname: AnsibleWorker01
        worker02:
          ansible_host: 172.31.91.167
          hostname: AnsibleWorker02
      vars:
        web_package: nginx 
  vars:
    ansible_sudo_pass: ubuntu 

    
